site_name: Users Analysis Facility (UAF) Documentation
theme:
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/ucsd.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
nav:
  - Home: "index.md"
  - Quick Start: 
      - Requesting an Account: "quickstart/requesting_account.md"
      - Access to XRootD Cluster: "quickstart/xrootd.md"
      - Old vs New UAFs: "quickstart/old_vs_new.md"
  - Setting up your Workspace:
      - Setting up Home: "setup/setting_up_home.md"
      - Setting up VOMS: "setup/setting_up_voms.md"
      - Using HTCondor: "setup/condor.md"
      - Using CEPH: "setup/ceph.md"
  - Miscellaneous:
      - Docker: "misc/using_docker.md"
      - JupyterHub @ UCSD: "misc/jupyterhub.md"

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true